### ISSUE TITLE
nmcliモジュールを何度実行してもステータスがchangedになる

### ISSUE THREAD

**Issue by nnstt1** [nnstt1/openshift_bastion#1]
nmcliモジュールを以下のargumentsで実行した場合、コントロールノードの設定内容は変わっていないのに何度実行してもansible実行結果のステータスがchangedになる

```
- name: main / Add internal ethernet connection
  nmcli:
    type: ethernet
    conn_name: "{{ internal_network.conn_name }}"
    ip4: "{{ internal_network.ipv4 }}"
    state: present
```
